### ISSUE TITLE
Tensor size mismatch while training

### ISSUE THREAD

**Issue by hariharanrl** [UNHSAILLab/SentimentalLIAR#1]
I was trying to reproduce the code but getting an error as in the attachment. can u please help??
![Error](https://user-images.githubusercontent.com/47934715/113095932-01ab4400-9212-11eb-96e0-016c7a888c40.png)

**Comment by iBibek** [comment]
> I was trying to reproduce the code but getting an error as in the attachment. can u please help??
> ![Error](https://user-images.githubusercontent.com/47934715/113095932-01ab4400-9212-11eb-96e0-016c7a888c40.png)

Hello,

Please install the transformers using pip install transformers==3 , this should solve the issue. If you are still facing any issues please let us know.

**Comment by hariharanrl** [comment]
ok I'll check , thanks for the quick response
